<?php

namespace Pumukit\PaellaStatsBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MultimediaObjectAnalyticsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultimediaObjectAnalyticsRepository extends DocumentRepository
{
}
