<?php
namespace Pumukit\StatsBundle\Repository;
use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserActionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserActionRepository extends DocumentRepository
{
}