<?php
namespace Pumukit\PaellaStatsBundle\Repository;
use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserActionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
<<<<<<< HEAD
class UserActionRepository extends DocumentRepository
{

}
=======
class UserActionRepository extends DocumentRepository {}
>>>>>>> feature/10_create_the_Action_to_obtain_most_used_browsers
